import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/Footer/Footer";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/themeProvider";
// import { NavBar } from "@/components/shared/Footer/NavBar";
import AuthProvider from "@/providers/AuthProvider";
import NavBar from "@/components/shared/navbar/nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "flex min-h-screen flex-col bg-background font-sans antialiased",
                    inter.className
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    <AuthProvider>
                        <NavBar></NavBar>
                        <main className="flex-grow">{children}</main>
                        <Footer />
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
